# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7f716eb13a612f17b2c97bceb166f0d40c8076bc6411386148b2a0230a9d3db49632e7f56f0900ba287e0da621feb5dc1090d2cb8e4311f54ac7ab3e3a9e2c4

test:
  secret_key_base: 941f30b500081399947bebff8d7996d7d322c533fd26fcac1934b212143bf58032b0deb5eddb59de11b98a08c6be052c25ddb8fea5070e7307a386ce00504951

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
